# Generated by Django 4.1 on 2022-10-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='produk_voucher',
            new_name='product_voucher',
        ),
    ]
