# Generated by Django 4.1 on 2022-11-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0002_rename_produk_voucher_voucher_product_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='product_voucher',
        ),
    ]
