# Generated by Django 4.1 on 2022-11-02 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100, null=True)),
                ('email', models.CharField(default=0, max_length=254, null=True)),
                ('mobile', models.CharField(default=0, max_length=20, null=True)),
                ('github', models.CharField(default=0, max_length=100, null=True)),
                ('instagram', models.CharField(default=0, max_length=100, null=True)),
                ('twitter', models.CharField(default=0, max_length=100, null=True)),
                ('facebook', models.CharField(default=0, max_length=100, null=True)),
                ('point', models.BigIntegerField(default=0)),
                ('weight', models.BigIntegerField(default=0)),
                ('profpic', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
