# Generated by Django 4.1 on 2022-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_alter_profile_profpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plastics',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(default=0, null=True, upload_to=None),
        ),
    ]
