# Generated by Django 4.1 on 2022-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_rename_plastics_profile_weight_alter_profile_profpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
