# Generated by Django 4.1 on 2022-10-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclehistory',
            old_name='is_pickedup',
            new_name='is_pickup',
        ),
    ]
