# Generated by Django 4.1 on 2022-11-02 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclehistory',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='is_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='name',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='point',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recyclehistory',
            name='weight',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
