# Generated by Django 4.1 on 2022-10-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_rename_is_pickedup_recyclehistory_is_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclehistory',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
