# Generated by Django 4.1 on 2022-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0003_recyclehistory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclehistory',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
