# Generated by Django 4.1 on 2022-10-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendeditem',
            name='image',
            field=models.CharField(default='/static/shopping/items/placeholder_item.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='recommendedvendor',
            name='image',
            field=models.CharField(default='/static/shopping/vendors/placeholder_vendor.jpg', max_length=255),
        ),
    ]
